import type { FormFieldMapping } from "@/country-config/types";

/**
 * ⚠️  STUB MAPPING — NOT SOURCED FROM THE REAL PORTUGUESE NATIONAL VISA
 * APPLICATION FORM ("Formulário de Pedido de Visto Nacional").
 *
 * No copy of the official form was available in this environment (checked:
 * files that looked promising turned out to be an unrelated Indian
 * health-insurance claim form, not the Portuguese visa form — see the
 * implementation plan for details). Every pdfFieldName below is invented
 * for the placeholder asset generated by
 * document-engine/form-fill/scripts/generate-stub-pdf.ts — it does NOT
 * correspond to any real government field name or layout.
 *
 * TODO(blocker-before-launch): obtain the real official PDF from a
 * Portuguese consulate / VFS / AIMA source, inspect its actual AcroForm
 * field names (or coordinates, if it's not a fillable form), and replace
 * every entry below. Do not ship to production until this file has been
 * replaced, isStub flipped to false, and this comment removed.
 *
 * Swapping in the real form later requires ONLY: (1) replace the PDF
 * asset, (2) update this mapping file, (3) re-run prisma/seed.ts to write
 * a new current CountryConfig row with a real sourceUrl. fill.ts,
 * generate.ts, and every UI component that reads isStub work unchanged.
 */
export const nationalVisaFormFieldMapping: FormFieldMapping = {
  formAssetPath: "document-engine/form-fill/assets/pt-d8-national-visa-form.STUB.pdf",
  isStub: true,
  fields: [
    { pdfFieldName: "stub_full_name", source: { questionId: "fullLegalName" } },
    { pdfFieldName: "stub_nationality", source: { questionId: "nationality" } },
    { pdfFieldName: "stub_current_country", source: { questionId: "currentCountry" } },
    { pdfFieldName: "stub_passport_number", source: { questionId: "passportNumber" } },
    { pdfFieldName: "stub_passport_expiry", source: { questionId: "passportExpiry" } },
    { pdfFieldName: "stub_employment_type", source: { questionId: "employmentType" } },
    {
      pdfFieldName: "stub_employer_or_clients",
      source: { questionId: "employerOrClientNames" },
    },
    { pdfFieldName: "stub_monthly_income", source: { questionId: "monthlyIncome" } },
    { pdfFieldName: "stub_income_currency", source: { questionId: "incomeCurrency" } },
    { pdfFieldName: "stub_has_dependents", source: { questionId: "hasDependents" } },
    { pdfFieldName: "stub_accommodation", source: { questionId: "accommodationDetails" } },
    { pdfFieldName: "stub_intended_move_date", source: { questionId: "intendedMoveDate" } },
  ],
};
